In [2]:
import numpy as np

EJERCICIO 1: Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
lista1 = [1,2,3,4,5,6,7,8,9,10]
ej1_1 = np.array(lista1)
ej1_1

ej1_2 = np.random.randint(0,100, (2,3))
ej1_2

ej1_3 = np.random.randint(0,100, (2,3,5))
ej1_3


array([[[52, 73, 33, 11, 99],
        [24, 42, 99, 25,  5],
        [29,  5, 69,  5, 81]],

       [[57,  7, 88, 19, 29],
        [41, 85, 46, 60,  4],
        [81,  2, 24,  5, 42]]])

EJERCICIO 2: Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [4]:
def propiedades_array(array):
    print(array.ndim)
    print(array.dtype)
    print(array.shape)
    print(array.size)

propiedades_array(ej1_1)
#propiedades_array(ej1_2)


1
int64
(10,)
10


EJERCICIO 3: Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [5]:
ej3 = np.eye(3,3)
ej3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

EJERCICIO 4: Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [6]:
ej4 = np.ones_like(ej1_3)
ej4


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

EJERCICIO 5: Es el momento de hacer algunas operaciones entre arrays
¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
Dividid las dos matricess

In [7]:
print('Shape ej1_2:',ej1_2.shape)
print('Shape ej3:', ej3.shape)
print('No se pueden sumar porque no tienen la misma forma. Devuelve el siguiente error:')
print('ej1_2 + ej3 = ValueError: operands could not be broadcast together with shapes (2,3) (3,3)') 
print('\n')
matriz_nueva = np.random.randint(0,100, (3,3))
print('Matriz nueva:', '\n',matriz_nueva)
print('Suma de matrices:', '\n', ej3 + matriz_nueva)

ej5_4 = np.multiply(matriz_nueva, ej3)
print('Multiplicación matrices:', '\n', ej5_4)
ej5_5 = np.divide(matriz_nueva, ej3)
print('División matrices:', '\n', ej5_5)


Shape ej1_2: (2, 3)
Shape ej3: (3, 3)
No se pueden sumar porque no tienen la misma forma. Devuelve el siguiente error:
ej1_2 + ej3 = ValueError: operands could not be broadcast together with shapes (2,3) (3,3)


Matriz nueva: 
 [[40 22 94]
 [64 32 94]
 [57 17 11]]
Suma de matrices: 
 [[41. 22. 94.]
 [64. 33. 94.]
 [57. 17. 12.]]
Multiplicación matrices: 
 [[40.  0.  0.]
 [ 0. 32.  0.]
 [ 0.  0. 11.]]
División matrices: 
 [[40. inf inf]
 [inf 32. inf]
 [inf inf 11.]]


/tmp/ipykernel_18960/3019674087.py:12: RuntimeWarning: divide by zero encountered in true_divide
  ej5_5 = np.divide(matriz_nueva, ej3)
