In [1]:
import numpy as np


EJERCICIO 1: Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:






In [2]:
array1 = np.random.randint(1,100,(5,3))
array1


array([[36, 24, 58],
       [51, 33, 77],
       [37, 78, 98],
       [48, 56, 14],
       [43, 91, 85]])

Ej1.1: El valor de la primera fila y la segunda columna.

In [3]:
array1[0,1]

24

Ej1.2: Los valores de la segunda fila y las dos primeras columnas.

In [5]:
array1[1,:2]

array([51, 33])

Ej1.3: Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [6]:
array1[0::2, :]

array([[36, 24, 58],
       [37, 78, 98],
       [43, 91, 85]])

Ej1.4: Extraed los valores que sean mayores que 0.5.

In [7]:
array1[array1 >0.5]

array([36, 24, 58, 51, 33, 77, 37, 78, 98, 48, 56, 14, 43, 91, 85])

Ej1.5: Extraed los valores menores que 0.2 o mayores que 0.5

In [9]:
array1[(array1 <0.2) | (array1>0.5)]

array([36, 24, 58, 51, 33, 77, 37, 78, 98, 48, 56, 14, 43, 91, 85])

EJERCICIO 2: Cread dos array de tres dimensiones:
El primero de 2 matrices, 5 filas y 3 columnas.
El segundo de 3 matrices, 2 filas y 5 columnas




In [11]:
array2 = np.random.randint(1,100,(2,5,3))
array3 = np.random.rand(3,2,5)
array2
array3

array([[[0.60065482, 0.01955357, 0.67144878, 0.20543188, 0.23601106],
        [0.3485933 , 0.309118  , 0.6372729 , 0.96279021, 0.24946762]],

       [[0.37749935, 0.5203915 , 0.94287361, 0.25189513, 0.46080852],
        [0.31406022, 0.80006445, 0.25185478, 0.8616759 , 0.46842936]],

       [[0.73918918, 0.54558048, 0.00596773, 0.52239058, 0.00977007],
        [0.4655607 , 0.20141541, 0.11082492, 0.63229381, 0.61357479]]])

Ej 2.1: Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [23]:
def propiedades_array(array):
    print(array.ndim)
    print(array.dtype)
    print(array.shape)
    print(array.size)

propiedades_array(array3)

3
float64
(3, 2, 5)
30


Ej 2.2: Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [17]:
#array2 + array3 
print('array2 y array3 no se pueden sumar porque no tienen la misma forma')

array2 y array3 no se pueden sumar porque no tienen la misma forma


Ej 2.3: Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas usando:
.reshape()
.transpose()

In [22]:
array3_cambiado = np.reshape(array3, (2,5,3))
array3_cambiado
print('La suma de los arrays con reshape:', '\n', array3_cambiado + array2)

La suma de los arrays con reshape: 
 [[[96.60065482 62.01955357 91.67144878]
  [41.20543188 65.23601106 74.3485933 ]
  [75.309118   10.6372729   4.96279021]
  [39.24946762 37.37749935 56.5203915 ]
  [97.94287361 61.25189513 26.46080852]]

 [[28.31406022 90.80006445  8.25185478]
  [31.8616759  18.46842936 53.73918918]
  [87.54558048 92.00596773 75.52239058]
  [76.00977007 25.4655607  12.20141541]
  [35.11082492 57.63229381 30.61357479]]]


In [26]:
array3_transpose = np.transpose(array3, (1,2,0))
print('Suma de array3 y array2 con transpose:', '\n', array3_transpose + array2)

Suma de array3 y array2 con transpose: 
 [[[96.60065482 62.37749935 91.73918918]
  [41.01955357 65.5203915  74.54558048]
  [75.67144878 10.94287361  4.00596773]
  [39.20543188 37.25189513 56.52239058]
  [97.23601106 61.46080852 26.00977007]]

 [[28.3485933  90.31406022  8.4655607 ]
  [31.309118   18.80006445 53.20141541]
  [87.6372729  92.25185478 75.11082492]
  [76.96279021 25.8616759  12.63229381]
  [35.24946762 57.46842936 30.61357479]]]
