In [20]:
import numpy as np

EJERCICIO 1: Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales.

In [21]:
matriz = np.random.rand(2,3,5)
matriz =np.round(matriz, decimals=1)
matriz

array([[[0.3, 1. , 0.9, 0.2, 0.2],
        [0.6, 0.9, 1. , 0.6, 0.9],
        [0.6, 0.6, 0.7, 0.5, 0.8]],

       [[0.4, 0.4, 0.9, 1. , 0.4],
        [0.1, 0.7, 0.2, 0.1, 0.1],
        [0. , 0.9, 0.2, 0.7, 0.5]]])

EJERCICIO 2: Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [22]:
media_matriz = np.mean(matriz)
media_matriz = np.round(media_matriz, decimals = 1)
print('La media del array es:', media_matriz)


La media del array es: 0.5


EJERCICIO 3: Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [23]:
max_matriz = np.max(matriz)
max_matriz = np.round(max_matriz, decimals = 1)
print('El numero máximo del array es:', max_matriz)

El numero máximo del array es: 1.0


EJERCICIO 4: Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [24]:
min_matriz = np.min(matriz)
min_matriz = np.round(min_matriz, decimals = 1)
print('El numero mínimo del array es:', min_matriz)

El numero mínimo del array es: 0.0


EJERCICIO 5: Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

In [25]:
matriz_vacia = np.empty_like((matriz), str)
matriz_vacia

for bloque in range(matriz.shape[0]):
    for fila in range(matriz.shape[1]):
        for columna in range(matriz.shape[2]):
            if matriz[bloque][fila][columna] == media_matriz:
                matriz_vacia[bloque][fila][columna] = "A"
            elif matriz[bloque][fila][columna] == max_matriz:
                matriz_vacia[bloque][fila][columna] = "D"
            elif matriz[bloque][fila][columna] == min_matriz:
                matriz_vacia[bloque][fila][columna] = "E"
            elif matriz[bloque][fila][columna] > media_matriz:
                matriz_vacia[bloque][fila][columna] = "B"
            elif matriz[bloque][fila][columna] < media_matriz:
                matriz_vacia[bloque][fila][columna] = "C"

matriz_vacia
        


array([[['C', 'D', 'B', 'C', 'C'],
        ['B', 'B', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'A', 'B']],

       [['C', 'C', 'B', 'D', 'C'],
        ['C', 'B', 'C', 'C', 'C'],
        ['E', 'B', 'C', 'B', 'A']]], dtype='<U1')

EJERCICIO 6: Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [29]:
array_vacio = np.empty(shape = 30, dtype = int)
index = 0

for bloque in range(matriz_vacia.shape[0]):
    for fila in range(matriz_vacia.shape[1]):
        for columna in range(matriz_vacia.shape[2]):
            letra = matriz_vacia[bloque][fila][columna]

            if letra == 'A' or letra == 'B':
                n=1
            elif letra == 'C' or letra == 'D':
                n=2
            else:
                n=3

            array_vacio[index] = n
            index += 1

array_vacio

array([2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 3, 1, 2, 1, 1])

In [31]:
array_vacio = np.reshape(array_vacio,(2,3,5))
array_vacio

array([[[2, 2, 1, 2, 2],
        [1, 1, 2, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 1, 2, 2],
        [2, 1, 2, 2, 2],
        [3, 1, 2, 1, 1]]])