In [2]:
import numpy as np

EJERCICIO 1: ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [3]:
np.random.seed(1)
array1 = np.random.random_sample((2,3))
array1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [4]:
np.random.seed(1)
array2 = np.random.random_sample((2,3))
array2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

EJERCICIO 2: Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [5]:
sol = np.random.uniform(0,10,size = (2,3,5))
sol = np.round(sol, decimals = 0)
sol

valores_unicos_sol = np.unique(sol)
valores_unicos_sol

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
cielo = np.random.binomial(10, 0.3, size = (2,3,5))
cielo

valores_unicos_cielo = np.unique(cielo)
valores_unicos_cielo

array([0, 1, 2, 3, 4, 5, 6])

EJERCICIO 3: En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

- Elementos comunes entre los dos arrays

- Unión de los dos arrays

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los 
valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [7]:
interseccion = np.intersect1d(sol,cielo)
print('Intersección de los arrays:',interseccion,'\n') #valores unicos comunes en los dos arrays

union = np.union1d(sol, cielo)
print('La unión de los arrays:',union,'\n')            #Une los valores de los arrays sin duplicados

diferencia_conjunta = np.setdiff1d(sol, cielo)
print('Los valores únicos en sol pero no en cielo:', diferencia_conjunta) #valores únicos que están en sol pero no en cielo
                                                                          #si cambiamos el orden de los arrays saldrán los que
                                                                          #están en cielo pero no en sol.

Intersección de los arrays: [0. 1. 2. 3. 4. 5. 6.] 

La unión de los arrays: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

Los valores únicos en sol pero no en cielo: [ 7.  8.  9. 10.]


EJERCICIO 4: Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.




In [8]:
array_1 = np.random.randint(0,100,(80))
print(array_1)

array_2 = np.random.randint(0,100,(80))
print(array_2)

[52 85 70  2 76 91 21 75  7 77 72 75 76 43 20 30 36  7 45 68 57 82 96 13
 10 23 81  7 24 74 92 20 32 12 65 94 60 24 82 97  2 92 98 10 54 96 82 86
 70 66 71 48 54 15  5 17 42 20 48 22 13 97 53 84 10 96 55 61 56 89 21 96
 83 25 14 13 84 43  6 77]
[56 59 15 24  9 66 71 53 69 36 21 40 77 91 49 47 77 40 78 45 87 16 28 45
 67 66 78 46  0 29 63 75 35 53 93 33  2 84 83 48 54 32 28 55 82 31 28 94
 74  8 99 32  8 84 77 50 79 41 64 83 24 20 44 15 30 91 14 19 26 86  7 99
 53 47 60 34 32 19 67 24]


- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [9]:
array_1 = np.unique(array_1)
array_2 = np.unique(array_2)
array_3 = np.setdiff1d(array_1, array_2)
array_4 = np.setdiff1d(array_2, array_1)
array_5 = np.intersect1d(array_1, array_2)

¿Cuál es la relación que existe entre todos estos arrays? 
💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [10]:
print(len(array_1))
print(len(array_2))
print(len(array_3))
print(len(array_4))
print(len(array_5))

print(len(array_1)+len(array_4)-len(array_5)==len(array_2)+len(array_3)-len(array_5))

54
57
26
29
28
True
